name: login
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  url_launcher: ^5.0.2
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.1+4
  cloud_firestore: ^0.9.5+2
  bottom_navy_bar: ^2.2.0
  firebase_core: ^0.3.1+1
  firebase_database: ^2.0.2  
  firebase_analytics: ^2.0.3
  mvc_pattern: ^3.2.3
  google_maps_flutter: ^0.4.0
  permission_handler: ^2.2.0
  location: ^2.3.2
  cached_network_image: ^0.7.0
  firebase_messaging: ^4.0.0+1
  firebase_storage: ^2.1.0+1
  fluttertoast: ^3.0.3
  shared_preferences: ^0.5.1+2
  image_picker: ^0.5.0+9
  intl: ^0.15.8
  geoflutterfire: ^2.0.3+2
  latlong: ^0.6.1
  sticky_headers: "^0.1.7"
  async_loader: ^0.1.1
  flutter_local_notifications: ^0.6.1
  http:
  flutter_webview_plugin: ^0.3.5
  grouped_buttons: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dog.jpg
    - assets/logo.png
    - assets/logo1.png
    - assets/alucard.jpg
    - assets/profileBG.png
    - assets/payUpLogo1Beta.png
    - assets/banks/American Express.PNG
    - assets/banks/Bank of America.PNG
    - assets/banks/BBVA.PNG
    - assets/banks/Capital One.PNG
    - assets/banks/Charles Schwab.PNG
    - assets/banks/Chase.PNG
    - assets/banks/citi.PNG
    - assets/banks/Fidelity.PNG
    - assets/banks/PNC.PNG
    - assets/banks/Regions.PNG
    - assets/banks/Simple.PNG
    - assets/banks/Suntrust.PNG
    - assets/banks/US Bank.PNG
    - assets/banks/USAA.PNG
    - assets/banks/Wells Fargo.PNG

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
    - family: Aguafina
      fonts:
        - asset: assets/Aguafina.ttf
    
    - family: Quantify
      fonts:
        - asset: assets/Quantify.ttf

    - family:  MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
